set -g mouse on

# Moving left
bind h select-pane -L
bind C-h select-pane -L

# Moving down
bind j select-pane -D
bind C-j select-pane -D

# Moving up
bind k select-pane -U
bind C-k select-pane -U

# Moving right
bind l select-pane -R
bind C-l select-pane -R

# tmux-ressurect
run-shell ~/clone/path/resurrect.tmux

# for vim
set -g @resurrect-strategy-vim 'session'
# for neovim
set -g @resurrect-strategy-nvim 'session'

set -g @resurrect-capture-pane-contents 'on'
